package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ArticulosServicios generated by hbm2java
 */
public class ArticulosServicios  implements java.io.Serializable {


     private ArticulosServiciosId id;
     private Articulos articulos;
     private Servicios servicios;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;

    public ArticulosServicios() {
    }

	
    public ArticulosServicios(ArticulosServiciosId id, Articulos articulos, Servicios servicios, int createdBy, Date createdAt, boolean deleted) {
        this.id = id;
        this.articulos = articulos;
        this.servicios = servicios;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
    }
    public ArticulosServicios(ArticulosServiciosId id, Articulos articulos, Servicios servicios, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted) {
       this.id = id;
       this.articulos = articulos;
       this.servicios = servicios;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
    }
   
    public ArticulosServiciosId getId() {
        return this.id;
    }
    
    public void setId(ArticulosServiciosId id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


