package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private long id;
     private String name;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;
     private Integer categoriasIdTipoArticulos;
     private Set<Inventarios> inventarioses = new HashSet<Inventarios>(0);
     private Set<ArticulosServicios> articulosServicioses = new HashSet<ArticulosServicios>(0);

    public Articulos() {
    }

	
    public Articulos(long id, String name, int createdBy, Date createdAt, boolean deleted) {
        this.id = id;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
    }
    public Articulos(long id, String name, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted, Integer categoriasIdTipoArticulos, Set<Inventarios> inventarioses, Set<ArticulosServicios> articulosServicioses) {
       this.id = id;
       this.name = name;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
       this.categoriasIdTipoArticulos = categoriasIdTipoArticulos;
       this.inventarioses = inventarioses;
       this.articulosServicioses = articulosServicioses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public Integer getCategoriasIdTipoArticulos() {
        return this.categoriasIdTipoArticulos;
    }
    
    public void setCategoriasIdTipoArticulos(Integer categoriasIdTipoArticulos) {
        this.categoriasIdTipoArticulos = categoriasIdTipoArticulos;
    }
    public Set<Inventarios> getInventarioses() {
        return this.inventarioses;
    }
    
    public void setInventarioses(Set<Inventarios> inventarioses) {
        this.inventarioses = inventarioses;
    }
    public Set<ArticulosServicios> getArticulosServicioses() {
        return this.articulosServicioses;
    }
    
    public void setArticulosServicioses(Set<ArticulosServicios> articulosServicioses) {
        this.articulosServicioses = articulosServicioses;
    }




}


