package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0



/**
 * ArticulosServiciosId generated by hbm2java
 */
public class ArticulosServiciosId  implements java.io.Serializable {


     private int articulosId;
     private int serviciosId;

    public ArticulosServiciosId() {
    }

    public ArticulosServiciosId(int articulosId, int serviciosId) {
       this.articulosId = articulosId;
       this.serviciosId = serviciosId;
    }
   
    public int getArticulosId() {
        return this.articulosId;
    }
    
    public void setArticulosId(int articulosId) {
        this.articulosId = articulosId;
    }
    public int getServiciosId() {
        return this.serviciosId;
    }
    
    public void setServiciosId(int serviciosId) {
        this.serviciosId = serviciosId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticulosServiciosId) ) return false;
		 ArticulosServiciosId castOther = ( ArticulosServiciosId ) other; 
         
		 return (this.getArticulosId()==castOther.getArticulosId())
 && (this.getServiciosId()==castOther.getServiciosId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getArticulosId();
         result = 37 * result + this.getServiciosId();
         return result;
   }   


}


