package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0



/**
 * CitasServiciosId generated by hbm2java
 */
public class CitasServiciosId  implements java.io.Serializable {


     private int citasId;
     private int serviciosId;

    public CitasServiciosId() {
    }

    public CitasServiciosId(int citasId, int serviciosId) {
       this.citasId = citasId;
       this.serviciosId = serviciosId;
    }
   
    public int getCitasId() {
        return this.citasId;
    }
    
    public void setCitasId(int citasId) {
        this.citasId = citasId;
    }
    public int getServiciosId() {
        return this.serviciosId;
    }
    
    public void setServiciosId(int serviciosId) {
        this.serviciosId = serviciosId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CitasServiciosId) ) return false;
		 CitasServiciosId castOther = ( CitasServiciosId ) other; 
         
		 return (this.getCitasId()==castOther.getCitasId())
 && (this.getServiciosId()==castOther.getServiciosId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCitasId();
         result = 37 * result + this.getServiciosId();
         return result;
   }   


}


