package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CitasServicios generated by hbm2java
 */
public class CitasServicios  implements java.io.Serializable {


     private CitasServiciosId id;
     private Citas citas;
     private Servicios servicios;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;

    public CitasServicios() {
    }

	
    public CitasServicios(CitasServiciosId id, Citas citas, Servicios servicios, int createdBy, Date createdAt, boolean deleted) {
        this.id = id;
        this.citas = citas;
        this.servicios = servicios;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
    }
    public CitasServicios(CitasServiciosId id, Citas citas, Servicios servicios, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted) {
       this.id = id;
       this.citas = citas;
       this.servicios = servicios;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
    }
   
    public CitasServiciosId getId() {
        return this.id;
    }
    
    public void setId(CitasServiciosId id) {
        this.id = id;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }




}


