package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private long id;
     private String name;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;
     private String lastName;
     private String address;
     private String telef1;
     private String telef2;
     private Set<Facturas> facturases = new HashSet<Facturas>(0);

    public Clientes() {
    }

	
    public Clientes(long id, String name, int createdBy, Date createdAt, boolean deleted, String lastName) {
        this.id = id;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
        this.lastName = lastName;
    }
    public Clientes(long id, String name, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted, String lastName, String address, String telef1, String telef2, Set<Facturas> facturases) {
       this.id = id;
       this.name = name;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
       this.lastName = lastName;
       this.address = address;
       this.telef1 = telef1;
       this.telef2 = telef2;
       this.facturases = facturases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelef1() {
        return this.telef1;
    }
    
    public void setTelef1(String telef1) {
        this.telef1 = telef1;
    }
    public String getTelef2() {
        return this.telef2;
    }
    
    public void setTelef2(String telef2) {
        this.telef2 = telef2;
    }
    public Set<Facturas> getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set<Facturas> facturases) {
        this.facturases = facturases;
    }




}


