package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private long id;
     private Clientes clientes;
     private String name;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;
     private Set<Inventarios> inventarioses = new HashSet<Inventarios>(0);

    public Facturas() {
    }

	
    public Facturas(long id, Clientes clientes, String name, int createdBy, Date createdAt, boolean deleted) {
        this.id = id;
        this.clientes = clientes;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
    }
    public Facturas(long id, Clientes clientes, String name, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted, Set<Inventarios> inventarioses) {
       this.id = id;
       this.clientes = clientes;
       this.name = name;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
       this.inventarioses = inventarioses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public Set<Inventarios> getInventarioses() {
        return this.inventarioses;
    }
    
    public void setInventarioses(Set<Inventarios> inventarioses) {
        this.inventarioses = inventarioses;
    }




}


