package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Inventarios generated by hbm2java
 */
public class Inventarios  implements java.io.Serializable {


     private long id;
     private Articulos articulos;
     private Citas citas;
     private Facturas facturas;
     private String name;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;
     private int cantidad;

    public Inventarios() {
    }

	
    public Inventarios(long id, Articulos articulos, String name, int createdBy, Date createdAt, boolean deleted, int cantidad) {
        this.id = id;
        this.articulos = articulos;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
        this.cantidad = cantidad;
    }
    public Inventarios(long id, Articulos articulos, Citas citas, Facturas facturas, String name, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted, int cantidad) {
       this.id = id;
       this.articulos = articulos;
       this.citas = citas;
       this.facturas = facturas;
       this.name = name;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
       this.cantidad = cantidad;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


