package modelo;
// Generated 18/11/2013 07:17:07 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private long id;
     private Categorias categorias;
     private String name;
     private int createdBy;
     private Date createdAt;
     private Integer updatedBy;
     private Date updatedAt;
     private boolean deleted;
     private Set<ArticulosServicios> articulosServicioses = new HashSet<ArticulosServicios>(0);
     private Set<CitasServicios> citasServicioses = new HashSet<CitasServicios>(0);

    public Servicios() {
    }

	
    public Servicios(long id, Categorias categorias, String name, int createdBy, Date createdAt, boolean deleted) {
        this.id = id;
        this.categorias = categorias;
        this.name = name;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.deleted = deleted;
    }
    public Servicios(long id, Categorias categorias, String name, int createdBy, Date createdAt, Integer updatedBy, Date updatedAt, boolean deleted, Set<ArticulosServicios> articulosServicioses, Set<CitasServicios> citasServicioses) {
       this.id = id;
       this.categorias = categorias;
       this.name = name;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.updatedBy = updatedBy;
       this.updatedAt = updatedAt;
       this.deleted = deleted;
       this.articulosServicioses = articulosServicioses;
       this.citasServicioses = citasServicioses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public Set<ArticulosServicios> getArticulosServicioses() {
        return this.articulosServicioses;
    }
    
    public void setArticulosServicioses(Set<ArticulosServicios> articulosServicioses) {
        this.articulosServicioses = articulosServicioses;
    }
    public Set<CitasServicios> getCitasServicioses() {
        return this.citasServicioses;
    }
    
    public void setCitasServicioses(Set<CitasServicios> citasServicioses) {
        this.citasServicioses = citasServicioses;
    }




}


